### ISSUE TITLE
Reformat stack.yaml

### ISSUE THREAD

**Issue by rcannon** [haskell-distributed/distributed-process-async#20]
Stack (>= 1.11) no longer supports this format for specifying extra dependencies to pull from github:
```
packages
- location:
    git: https://github.com/bitemyapp/esqueleto.git
    commit: 08c9b4cdf977d5bcd1baba046a007940c1940758
  extra-dep: true
```
See [here](https://docs.haskellstack.org/en/stable/yaml_configuration/#packages) for details.
